- .gitignore
- Pipfile
- Pipfile.lock
- tests/projects/repo/test_repo.py
- tests/projects/test_load.py
- tests/stages/test_discovery.py
- tests/steps/deploy/k8s/test_k8s.py
- tests/steps/test_steps.py
- tests/test_project.py
because:
- it is compatible with unittest
- allows for parameterized tests
- has better filtering support
- is very widely used
branch: feature/ARC-488-switch-to-pytest
> [ARC-488] Switch to pytest

- src/mpyl/cli/build.py
- src/mpyl/cli/commands/build/jenkins.py
- src/mpyl/steps/deploy/k8s/chart.py
- src/mpyl/utilities/jenkins/runner.py
- tests/steps/deploy/k8s/test_k8s.py
- tests/test_resources/test_project.yml
There’s a whitelist target defined for TEST, but we’re deploying a PR therefore the configured whitelists `configured.get_value(self.target)` is None, which then throws an exception when the list is extended
Example run: https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline/view/change-requests/job/PR-10515/3/console
project.yml that triggered this: https://github.com/Vandebron/Vandebron/blob/c29489fd64c9a0e97345b4ce8c6183381c1ca784/energy-trading/curtailment/curtailment-volumes-api/deployment/project.yml#L90C1-L92
> [TECH-434] Fix adding whitelists when none is defined for target

- mpyl-example.py
- run_properties.yml
- src/mpyl/reporting/targets/github.py
- tests/reporting/targets/test_github.py
- tests/test_resources/run_properties.yml
Monorepo counterpart https://github.com/Vandebron/Vandebron/pull/10546
----
🏗️ Build [10](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-125/10/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀  *enrichChargeSessionsJob*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-125.test.nl/)*, *[sbtservice](https://sbtservice-125.test.nl/)*  
[TECH-441]: https://vandebron.atlassian.net/browse/TECH-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> append info to github pr body

- Jenkinsfile
----
📕 [TECH-430](https://vandebron.atlassian.net/browse/TECH-430) Monorepo runner should update installed `mpyl` if it doesn't match the version specified ![ewaldschrader@vandebron.nl](https://secure.gravatar.com/avatar/22987b802af30079346039ff7c67e6fa?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FES-1.png) 
[p1684851291017589](https://vandebron.slack.com/archives/C04KP2UFMMJ/p1684851291017589) 
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-135/2/display/redirect) ✅ Successful, started by _Ewald Schrader_  
🚀  *enrichChargeSessionsJob*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-135.test.nl/)*, *[sbtservice](https://sbtservice-135.test.nl/)*  
[TECH-430]: …
> fix mpyl version

- Jenkinsfile
branch: feature/TECH-465-investigate-mpyl-config-solution
This allows people to test their mpyl pr's if they also made changes to the config & schema.
----
📕 [TECH-465](https://vandebron.atlassian.net/browse/TECH-465) Investigate better solution for mpyl_config repo ![jorgpost@vandebron.nl](https://secure.gravatar.com/avatar/4438c9af956adc9562fde9f029f624e2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FJP-3.png) 
Currently you can’t really update the mpyl_config for mpyl pr builds, because once you push a change the yml validation will fail on other pr builds.
🏗️ Build [4](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-139/4/display/redirect) ✅ Successful, started by _Jorg Post_  
🚀 …
> [TECH-465] Add an option to select a branch to use for mpyl_config repo

- src/mpyl/utilities/subprocess/__init__.py
branch: feature/TECH-457_fix_subprocess_result
----
📕 [TECH-457](https://vandebron.atlassian.net/browse/TECH-457) Fix master pipeline <img src="https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/6151b89d72f6970069e87968/a94f6e9a-3a6b-434f-926f-f4aa079c6a59/24" width="24" height="24" alt="danielkoves@vandebron.nl" /> 
Seems like we broke the master pipeline again
Master pipeline should build all projects and not fail fast → this part should be fixed with [142](https://github.com/Vandebron/mpyl/pull/142) 
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-154/2/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀 *[cloudfront-service](https://cloudfront-service-154.test.nl/)*, *enrichChargeSessionsJob*, *job*, …
> [TECH-457] Fix subprocess reporting

- .github/workflows/build-package.yml
- .idea/.gitignore
- mpyl-example.py
- run_properties.yml
- src/mpyl/cli/commands/build/mpyl.py
- src/mpyl/cli/commands/health/checks.py
- src/mpyl/reporting/targets/github.py
- src/mpyl/reporting/targets/jira.py
- src/mpyl/reporting/targets/slack.py
- src/mpyl/schema/run_properties.schema.yml
- src/mpyl/stages/discovery.py
- src/mpyl/steps/__init__.py
- src/mpyl/steps/build/echo.py
- src/mpyl/steps/collection.py
- src/mpyl/steps/models.py
- src/mpyl/steps/steps.py
- src/mpyl/utilities/repo/__init__.py
- tests/cli/commands/test_build.py
- tests/reporting/targets/test_github.py
- tests/reporting/targets/test_reporters.py
- tests/reporting/targets/test_resources/markdown_jira_ticket_to_github.md
- tests/stages/test_discovery.py
- tests/steps/test_steps.py
- tests/test_resources/mpyl_config.yml
- tests/test_resources/run_properties.yml
- tests/test_resources/test_minimal_project.yml
- tests/utilities/test_s3.py
Replacing the Stage enum with a dynamic set of stages that can be configured via `mpyl_config` requires significant refactorings.
In order to limit the scope of the work, this PR concerns itself with preparational work and small bugfixes only. In particular:
Note: `.env` in the monorepo should not contain `MPYL_CONFIG_PATH=deployment/pipeline/mpyl/config.yml` in case it still does. Perhaps you could make sure that `mpyl build status` and `mpyl health` still work on the monorepo.
----
At the moment stages are a hardcoded concept in MPyL [steps.py#L60-L85](https://github.com/Vandebron/mpyl/blob/37c7b0c9a7e9eb54dfb05d8822c4e360469855b7/src/mpyl/steps/steps.py#L60-L85) 
While there is potential order dependency between build steps, a fixed order is too limiting. For example, a *security scan_ …
> Prepare for customizable stages

- src/mpyl/schema/mpyl_config.schema.yml
- src/mpyl/steps/deploy/k8s/chart.py
- src/mpyl/steps/models.py
- src/mpyl/steps/postdeploy/cypress_test.py
- src/mpyl/utilities/cypress/__init__.py
- src/mpyl/utilities/docker/__init__.py
This makes the cypress runs almost as fast as the nightly runs that use jenkins matrixes. Increasing performance on longer suites more than 2x.
branch: feature/TECH-394-implement-parallel-runs
----
Make sure that certain cypress suites get triggered for certain projects when specified in the project.yml.
🏗️ Build [10](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-144/10/display/redirect) ✅ Successful, started by _Jorg Post_  
🚀 *[cloudfront-service](https://cloudfront-service-144.test.nl/)*, *enrichChargeSessionsJob*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-144.test.nl/)*, *[sbtservice](https://sbtservice-144.test.nl/)*  
[TECH-394]: https://vandebron.atlassian.net/browse/TECH-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
> [TECH-394] Add multiprocess support to the cypress step

- src/mpyl/cli/commands/build/mpyl.py
- src/mpyl/utilities/repo/__init__.py
This is required since we are comparing to the local main branch in `changes_in_branch`. If you have rebased/merged the latest main branch into your pr but your local main branch is behind, it will detect those extra changes as changes of your branch. The previous 'pull' function gave an error when running mpyl locally on main because you're not supposed to fetch into your current branch (without `--update-head-ok`)
----
> Add an actual pull to update the local main branch when needed

- src/mpyl/cli/health.py
- src/mpyl/steps/deploy/k8s/__init__.py
- src/mpyl/steps/deploy/k8s/chart.py
- src/mpyl/steps/deploy/k8s/resources/prometheus.py
- src/mpyl/steps/deploy/k8s/resources/schema/monitoring.coreos.com_prometheuses.schema.yml
- src/mpyl/steps/deploy/k8s/resources/schema/monitoring.coreos.com_servicemonitors.schema.yml
- tests/projects/cloudfront/deployment/project.yml
- tests/steps/deploy/k8s/chart/templates/service/service-monitor.yaml
- tests/steps/deploy/k8s/test_k8s.py
branch: feature/TECH-529-implement-service-monitor
----
[p1692280104683939](https://vandebron.slack.com/archives/C04KP2UFMMJ/p1692280104683939) 
🏗️ Build [5](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-189/5/display/redirect) ✅ Successful, started by _Jorg Post_  
🚀 *[cloudfront-service](https://cloudfront-service-189.test.nl/)*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-189.test.nl/)*, *[sbtservice](https://sbtservice-189.test.nl/)*, *sparkJob*  
[TECH-529]: https://vandebron.atlassian.net/browse/TECH-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TECH-529] Implement service monitor chart

- src/mpyl/project.py
- src/mpyl/steps/deploy/k8s/chart.py
- tests/steps/deploy/k8s/chart/templates/service/deployment.yaml
- tests/test_resources/test_project.yml
- Correctly parse instance (replica) numbers from project yaml (it was not under `deployment.kubernetes.resources.limit` but under `deployment.kubernetes.resources`)
- Take into account not only `deployment.kubernetes.resources.limit` but `deployment.kubernetes.resources.request` as well
----
> Correctly parse resource requests and replica count

- releases/README.md
- releases/notes/1.0.10.md
- releases/notes/1.0.11.md
- tests/test_documentation.py
A little fix for the table of contents in the documentation
branch: fix/TECH-470-clean-release-notes
----
Currently we have many very similar Jenkinsfiles, python runners etc in three different repos:
* mpyl repo
* monorepo
* scripting
Figure out a way to centralise these, or to have safeguards to not break them with a breaking change
----
The github action to sync Jenkinsfiles back to the scripting repo could be a good starting point for keeping the repo-runners synced
[https://github.com/Vandebron/Vandebron/blob/master/.github/workflows/push*Jenkinsfile_to_scripting.yml](https://github.com/Vandebron/Vandebron/blob/master/.github/workflows/push_Jenkinsfile_to*scripting.yml) 
Things like repository link, mpyl*config path and run*properties path would need to be configurable/overwriteable …
> [TECH-470] Prevent titles in release notes from messing up the TOC

- src/mpyl/project.py
- src/mpyl/schema/mpyl_config.schema.yml
- src/mpyl/schema/project.schema.yml
- src/mpyl/steps/deploy/cloudfront_kubernetes_deploy.py
- src/mpyl/utilities/s3/__init__.py
- tests/projects/cloudfront/deployment/project.yml
- tests/utilities/test_s3.py
Making the access and secret keys optional in the config as it's very common to use AWS credential or config files for authentication. Boto3 will automatically look for these files if nothing is passed to the client.
branch:feature/TECH-477-aws-credentials
local build reading from credentials file:
----
Use `boto3}} or read manually from {{~/.aws/credentials` if there are no AWS environment variables
github token is handled at: `mpyl.cli.commands.build.jenkins.get_token` as an example
🏗️ Build [19](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-196/19/display/redirect) ✅ Successful, started by _Ben Lynch_  
🚀 *[cloudfront-service](https://cloudfront-service-196.test.nl/)*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-196.test.nl/)*, …
> [TECH-477] Updating AWS credential requirements

- Jenkinsfile
- MANIFEST.in
Output in build:
```
MPyL 208.2410
Latest public release 1.0.11
```
branch: fix/TECH-470-include-releases-info-in-library
----
Currently we have many very similar Jenkinsfiles, python runners etc in three different repos:
* mpyl repo
* monorepo
* scripting
Figure out a way to centralise these, or to have safeguards to not break them with a breaking change
----
The github action to sync Jenkinsfiles back to the scripting repo could be a good starting point for keeping the repo-runners synced
[https://github.com/Vandebron/Vandebron/blob/master/.github/workflows/push*Jenkinsfile_to_scripting.yml](https://github.com/Vandebron/Vandebron/blob/master/.github/workflows/push_Jenkinsfile_to*scripting.yml) 
Things like repository link, mpyl*config path and run*properties path would need to be …
> [TECH-470] Correct pattern for releases.txt

- Jenkinsfile
- releases/README.md
- releases/notes/1.0.11.md
- src/mpyl/reporting/targets/jira.py
@SamTheisens Sometimes the pipeline can fail with "WARNING: Could not handle Jira ticket EVA-885: You do not have permission to assign issues" and then mark the pipeline as unstable.
Also it's a bit annoying that if you trigger a build on a PR it gets assigned to you, even if it's not your PR
----
🏗️ Build [13](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-202/13/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀 *[cloudfront-service](https://cloudfront-service-202.test.nl/)*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-202.test.nl/)*, *[sbtservice](https://sbtservice-202.test.nl/)*, *sparkJob*  
[TECH-554]: https://vandebron.atlassian.net/browse/TECH-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
> [TECH-554] Do not reassign ticket

- src/mpyl/utilities/repo/__init__.py
branch: feature/TECH-507-revert-base-revision-change
----
[181](https://github.com/Vandebron/mpyl/issues/181) 
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-230/2/display/redirect) ✅ Successful, started by _Jorg Post_  
🚀 *[cloudfront-service](https://cloudfront-service-230.test.nl/)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-230.test.nl/)*, *[sbtservice](https://sbtservice-230.test.nl/)*, *sparkJob*  
[TECH-507]: https://vandebron.atlassian.net/browse/TECH-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TECH-507] Revert the change to the base revision

- src/mpyl/cli/build.py
- src/mpyl/cli/commands/build/jenkins.py
mpyl CLI jenkins improvements
----
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-235/2/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀 *[cloudfront-service](https://cloudfront-service-235.test.nl/)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-235.test.nl/)*, *[sbtservice](https://sbtservice-235.test.nl/)*, *sparkJob*  
[TECH-569]: https://vandebron.atlassian.net/browse/TECH-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TECH-513] Ask for target input when deploying a tag

- src/mpyl/schema/mpyl_config.schema.yml
@SamTheisens  somehow the release notes commit 1de6bc5a0fae3e8f65586712e2bc7905a8d26f35 got rid of the Dagster definition section in the schema.
If that was not an accident, let's discuss :-) if it was an accident, this is the PR to revert it 😄 
----
> Readd Dagster definition section in mpyl-config-yaml-schema

- mpyl_config.example.yml
- src/mpyl/project.py
- src/mpyl/projects/versioning.py
- src/mpyl/schema/mpyl_config.schema.yml
- src/mpyl/schema/project.schema.yml
- src/mpyl/steps/build/docker_after_build.py
- src/mpyl/steps/build/dockerbuild.py
- src/mpyl/steps/deploy/dagster.py
- src/mpyl/steps/deploy/k8s/resources/dagster.py
- src/mpyl/steps/test/dockertest.py
- src/mpyl/utilities/docker/__init__.py
- tests/reporting/__init__.py
- tests/steps/deploy/k8s/test_k8s.py
- tests/steps/post_deploy/test_cypress.py
- tests/steps/test_steps.py
- tests/test_resources/mpyl_config.yml
- tests/test_resources/test_data.py
- tests/test_resources/upgrades/mpyl_config_upgraded.yml
- tests/utilities/test_docker.py
----
In order to be able to deploy to different registries based on the projects that we are building.
Needed for NUC deployments.
**How**
* Check how it’s done in MPL
* Improve upon it in MPyL → `Docker After Build` step
* Default config should be bigdataregistry, but we should be able to override that with a config
🏗️ Build [10](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-212/10/display/redirect) ✅ Successful, started by _Sam Theisens_  
🚀 *[cloudfront-service](https://cloudfront-service-212.test.nl/swagger/index.html)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-212.test.nl/swagger/index.html)*, *[sbtservice](https://sbtservice-212.test.nl/swagger/index.html)*, *sparkJob*  
[TECH-117]: …
> [TECH-117] Support multiple Docker registries

- Jenkinsfile
- src/mpyl/cli/commands/projects/lint.py
- src/mpyl/cli/projects.py
- src/mpyl/project.py
- tests/cli/commands/test_cli.py
The logic was quite complicated and implicit. Its only goal was to filter out overridden projects. It's probably simpler and cleaner to just make sure that the base projects comply with the schema, while we're waiting for a different solution to deployment variations.   
branch: feature/TECH-488-filter-out-project-overrides
----
Check namespace replacement
URLs should be interpolated with the name of the project
Add a command to `mpyl build health` to validate unique project names
* after loading all the projects, validating the yamls then check project names
* fail pipeline if project name is not unique
* check all project names in lower case -> give suggestions if there's a case-sensitity issue
create post about this logic + add it to mpyl documentation
🏗️ Build …
> [TECH-488] Remove filtering from project commands

- .pylintrc
- run_properties.yml
- src/mpyl/project.py
- src/mpyl/projects/versioning.py
- src/mpyl/reporting/targets/jira.py
- src/mpyl/schema/k8s_api_core.schema.yml
- src/mpyl/schema/project.schema.yml
- src/mpyl/steps/deploy/k8s/chart.py
- src/mpyl/steps/deploy/k8s/resources/spark.py
- tests/projects/test_versioning.py
- tests/steps/deploy/k8s/chart/templates/service/deployment.yaml
- tests/steps/deploy/k8s/chart/templates/service/role.yaml
- tests/steps/deploy/k8s/chart/templates/service/rolebinding.yaml
- tests/steps/deploy/k8s/chart/templates/spark/role.yaml
- tests/steps/deploy/k8s/chart/templates/spark/rolebinding.yaml
- tests/steps/deploy/k8s/chart/templates/spark/spark.yaml
- tests/steps/deploy/k8s/templates/manifest.yaml
- tests/steps/deploy/k8s/test_k8s.py
- tests/test_resources/test_project.yml
- tests/test_resources/upgrades/test_project_1_0_10.yml
- tests/test_resources/upgrades/test_project_1_0_11.yml
- tests/test_resources/upgrades/test_project_1_0_8.yml
- tests/test_resources/upgrades/test_project_1_0_9.yml
- tests/test_resources/upgrades/test_project_1_3_1.yml
----
🏗️ Build [5](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-265/5/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀 *[cloudfront-service](https://cloudfront-service-265.test.nl/swagger/index.html)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-265.test.nl/swagger/index.html)*, *[sbtservice](https://sbtservice-265.test.nl/swagger/index.html)*, *sparkJob*  
[TECH-630]: https://vandebron.atlassian.net/browse/TECH-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix/TECH 630 Implement missing project yaml fields

- src/mpyl/cli/commands/projects/lint.py
- src/mpyl/cli/projects.py
- tests/cli/commands/test_cli.py
Lint the whitelisting rules defined in the project yamls when doing `mpyl projects lint --extended`
Monorepo run:
```
Running extended checks...
Checking namespace substitution: 
❌ Project batterypackApi has wrong namespace substitutions:
OCPP_URL references unrecognized project ocpp-master
❌ Project chargeCardEcedoSyncJob has wrong namespace substitutions:
SFSYNC_URL references unrecognized project sfsync (did you mean sfSync?)
❌ Project chargePointEcedoSyncJob has wrong namespace substitutions:
SFSYNC_URL references unrecognized project sfsync (did you mean sfSync?)
❌ Project mockservice has wrong namespace substitutions:
BATTERY_API_URL references unrecognized project batteryApi
GENERATOR_API_URL references unrecognized project generatorApi
❌ Project publicApiVPP has wrong namespace …
```
> [TECH-546] Lint whitelisting rules

- tests/cli/commands/test_cli.py
----
**What**
We currently do not support project yaml overrides in MPyL. It is also interfering with the namespace linkup linting step (because the project name is dynamic).
Teams indicated that they are going to migrate some project away from using these overrides, see: [2023-07-26+CI+CD+Guild](https://vandebron.atlassian.net/wiki/spaces/DIG/pages/95581484646441/2023-07-26+CI+CD+Guild) 
For the rest, come up with a plan on how to migrate them, talk to teams that have projects like that.
For argo, take a look at applicationset: [](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/) 
----
**How**
There’s a main project yaml and override yamls. The override yaml should be attached to the main one which create a new project.
Current shortcomings:
* env vars need to be …
> [TECH-494] Make tests runnable on Linux

- releases/README.md
- releases/notes/1.3.2.md
- src/mpyl/reporting/targets/jira.py
branch: feature/TECH-660-remove-jira-ticket-transitions
----
There were quite some complaints about mpyl (wrongly) moving Jira tickets to different states, so remove this functionality.
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-279/2/display/redirect) ✅ Successful, started by _Jorg Post_  
🚀 *[cloudfront-service](https://cloudfront-service-279.test.nl/swagger/index.html)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-279.test.nl/swagger/index.html)*, *[sbtservice](https://sbtservice-279.test.nl/swagger/index.html)*, *sparkJob*  
[TECH-660]: https://vandebron.atlassian.net/browse/TECH-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TECH-660] Hardcode the jira so that we're sure it only moves tickets from todo to inprogress

- src/mpyl/build.py
- src/mpyl/cli/build.py
- src/mpyl/project.py
- tests/cli/commands/test_build.py
- tests/projects/test_versioning.py
- tests/steps/deploy/k8s/chart/templates/service/prometheus-rule.yaml
- tests/steps/deploy/k8s/templates/manifest.yaml
- tests/test_resources/test_data.py
- tests/test_resources/test_project.yml
- tests/test_resources/upgrades/test_project_1_0_10.yml
- tests/test_resources/upgrades/test_project_1_0_11.yml
- tests/test_resources/upgrades/test_project_1_0_8.yml
- tests/test_resources/upgrades/test_project_1_0_9.yml
- tests/test_resources/upgrades/test_project_1_3_1.yml
Fixes #282
I looked back in history for clues as to why this `typ="unsafe"` is needed, and apparently it was done [for performance reasons](https://github.com/Vandebron/mpyl/commit/2b7bee0b9f81841d7b47691b74b12312f9556102#diff-8ab9ddcdb8fee93bb0c9016ade42a4f20cb40bcfa5fd27e03d014c3c5725a542R348).
My suggestion is to disable this setting since it seems to be causing more harm than benefit. 
----
> Move YAML parser back to default settings

- releases/README.md
- releases/notes/1.4.0.md
- releases/notes/1.4.1.md
- src/mpyl/cli/build.py
- src/mpyl/reporting/formatting/text.py
- src/mpyl/reporting/targets/jira.py
- tests/reporting/formatting/test_resources/simple_run.txt
- tests/reporting/formatting/test_resources/simple_test.txt
- tests/reporting/test_simple_reporting.py
1. 
When a lot of tests are being run, the github check of the pipeline cannot be updated because:
```
Unexpected exception: 422 {"message": "Invalid request.\n\nOnly 65535 characters are allowed; 133237 were supplied.", "documentation_url":                   
"https://docs.github.com/rest/checks/runs#update-a-check-run"}  
```
Do not update the check with all the individual test cases, but only push a summary
2. 
Fix target branch for tag builds in artifacts repo 
3. 
Filter epics from to do transitions
----
`lostSdePerMwhInEuros` is used in the curtailment decision logic. It is determiend as follows (with a **floor of 0**):
```python
if estimatedSdeCorrectionPriceInEuros < baseElectricityPriceInEuros:
lostSdePerMwhInEuros = tenderPriceInEuros - baseElectricityPriceInEuros
else: …
```
> fix/FTS 691 Improvements

- src/mpyl/steps/deploy/dagster.py
- src/mpyl/steps/deploy/k8s/__init__.py
branch: bug/TECH-599-fix-dockerconfig-creation
----
[2926](https://github.com/Vandebron/scripting/pull/2926)  needs to be merged first (linting and updating of runner and config)
----
to test the behaviour of two user-code repositories co-existing (MPL and MPyL dpeloyed) I would like to:
test out a usercode deployment on Acceptance:
* make backup of the workspace.yml file (copy YAML and store locally)
* deploy a tag with MPL (suf or so)
* then deploy the same tag with MPyL
* check if everything’s still working
the results of this test will decide whether a hard-switch for ALL projects is needed or what steps can be done to make a softer switch happen/.
----
check in with Tim (platform) about the workspace-configmap backup
----
check on how to deprecate a Jenkinspipeline?
----
* fix …
> [TECH-599] Use docker config instead of dockerRegistryConfig

- README-dev.md
- releases/notes/1.4.2.md
branch: feature/TECH-599-prepare-release-notes-for-1.4.2
----
[2926](https://github.com/Vandebron/scripting/pull/2926)  needs to be merged first (linting and updating of runner and config)
----
to test the behaviour of two user-code repositories co-existing (MPL and MPyL dpeloyed) I would like to:
test out a usercode deployment on Acceptance:
* make backup of the workspace.yml file (copy YAML and store locally)
* deploy a tag with MPL (suf or so)
* then deploy the same tag with MPyL
* check if everything’s still working
the results of this test will decide whether a hard-switch for ALL projects is needed or what steps can be done to make a softer switch happen/.
----
check in with Tim (platform) about the workspace-configmap backup
----
check on how to deprecate a Jenkinspipeline?
----
* …
> [TECH-599] Prepare release notes

- src/mpyl/project.py
- src/mpyl/steps/deploy/k8s/chart.py
- src/mpyl/steps/deploy/k8s/resources/traefik.py
- src/mpyl/steps/deploy/kubernetes.py
- tests/steps/deploy/k8s/chart/templates/cronjob/cronjob.yaml
- tests/steps/deploy/k8s/chart/templates/ingress-prod/minimalService-ingress-0-https.yaml
- tests/steps/deploy/k8s/chart/templates/ingress/minimalService-ingress-0-https.yaml
- tests/steps/deploy/k8s/chart/templates/job/job.yaml
- tests/steps/deploy/k8s/chart/templates/job/service-account.yaml
- tests/steps/deploy/k8s/chart/templates/service/deployment.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-0-http.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-0-https.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-0-whitelist.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-1-http.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-1-https.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-1-whitelist.yaml
- tests/steps/deploy/k8s/chart/templates/service/prometheus-rule.yaml
- tests/steps/deploy/k8s/chart/templates/service/role.yaml
- tests/steps/deploy/k8s/chart/templates/service/rolebinding.yaml
- tests/steps/deploy/k8s/chart/templates/service/service-account.yaml
- tests/steps/deploy/k8s/chart/templates/service/service-monitor.yaml
- tests/steps/deploy/k8s/chart/templates/service/service.yaml
- tests/steps/deploy/k8s/chart/templates/spark/config-map.yaml
- tests/steps/deploy/k8s/chart/templates/spark/role.yaml
- tests/steps/deploy/k8s/chart/templates/spark/rolebinding.yaml
- tests/steps/deploy/k8s/chart/templates/spark/service-account.yaml
- tests/steps/deploy/k8s/templates/manifest.yaml
- tests/steps/deploy/k8s/test_k8s.py
----
🏗️ Build [3](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-299/3/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀 *[cloudfront-service](https://cloudfront-service-299.test.nl/swagger/index.html)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-299.test.nl/swagger/index.html)*, *ocpp-first*, *ocpp-second*, *[sbtservice](https://sbtservice-299.test.nl/swagger/index.html)*, *sparkJob*  
[TECH-694]: https://vandebron.atlassian.net/browse/TECH-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feature/TECH 694 Improve traefik config

- releases/notes/1.4.4.md
- src/mpyl/steps/build/docker_build.py
- src/mpyl/steps/test/dockertest.py
- src/mpyl/utilities/docker/__init__.py
----
[2926](https://github.com/Vandebron/scripting/pull/2926)  needs to be merged first (linting and updating of runner and config)
----
to test the behaviour of two user-code repositories co-existing (MPL and MPyL dpeloyed) I would like to:
test out a usercode deployment on Acceptance:
* make backup of the workspace.yml file (copy YAML and store locally)
* deploy a tag with MPL (suf or so)
* then deploy the same tag with MPyL
* check if everything’s still working
the results of this test will decide whether a hard-switch for ALL projects is needed or what steps can be done to make a softer switch happen/.
----
check in with Tim (platform) about the workspace-configmap backup
----
check on how to deprecate a Jenkinspipeline?
----
* fix linting errors (check mpyl lint --all)
**** deprecate …
> [DATA-1165] Add env var to Docker Build

- releases/notes/1.4.5.md
- src/mpyl/schema/mpyl_config.schema.yml
- src/mpyl/steps/deploy/dagster.py
- src/mpyl/steps/deploy/k8s/resources/dagster.py
- src/mpyl/utilities/dagster/__init__.py
- tests/steps/deploy/dagster/dagster-user-deployments/values.yaml
- tests/steps/deploy/dagster/dagster-user-deployments/values_with_global_service_account.yaml
- tests/steps/deploy/dagster/dagster-user-deployments/values_without_global_service_account.yaml
- tests/steps/deploy/dagster/test_dagster.py
This is to recreate the current behaviour of MPL's DagsterDeploy step of having one single serviceAccount for all dagster user deployment helm charts.
The override ServiceAccount can be configured via `mpyl_config`
For example: FTS's user deployment needs to be able to access resources in a different namespace in order to spawn their scheduled pods. With the base ServiceAccount that the dagster user deployment helm chart is creating, this is not possible, as it doesnt have the ClusterroleBindings that require this kind of action. The ClusterroleBindings are being created and maintained by the platform team. 
----
This EPIC replaces [ESFA-851](https://vandebron.atlassian.net/browse/ESFA-851) 
**Why**
KNMI will upgrade their current HARMONIE model, which means that we’ll have to also adopt …
> [DATA-1165] Global serviceaccountname override possibility for dagster helm charts

- releases/notes/1.4.6.md
- src/mpyl/cli/commands/projects/lint.py
- src/mpyl/cli/projects.py
branch: feature/TECH-706_fail_on_extended_lint
----
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-313/2/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀 *[cloudfront-service](https://cloudfront-service-313.test.nl/swagger/index.html)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-313.test.nl/swagger/index.html)*, *ocpp-first*, *ocpp-second*, *[sbtservice](https://sbtservice-313.test.nl/swagger/index.html)*, *sparkJob-first*, *sparkJob-second*  
[TECH-706]: https://vandebron.atlassian.net/browse/TECH-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TECH-706] Fail after all extended checks are run

- releases/notes/1.4.8.md
- src/mpyl/__init__.py
- src/mpyl/build.py
- src/mpyl/project.py
- src/mpyl/stages/discovery.py
- src/mpyl/steps/deploy/kubernetes.py
- src/mpyl/steps/deploy/kubernetes_job.py
- src/mpyl/steps/deploy/kubernetes_spark_job.py
- tests/stages/test_discovery.py
- Add debug logs when doing `mpyl build --verbose status`
- Fix a bug with project path startswith
----
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-321/2/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀 *[cloudfront-service](https://cloudfront-service-321.test.nl/swagger/index.html)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-321.test.nl/swagger/index.html)*, *ocpp-first*, *ocpp-second*, *[sbtservice](https://sbtservice-321.test.nl/swagger/index.html)*, *sparkJob-first*, *sparkJob-second*  
[TECH-702]: https://vandebron.atlassian.net/browse/TECH-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TECH-702] Explain build status

- src/mpyl/cli/build.py
- src/mpyl/steps/run_properties.py
branch: featute/TECH-713-fix-tag-builds
----
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-326/2/display/redirect) ✅ Successful, started by _Jorg Post_  
🚀 *[cloudfront-service](https://cloudfront-service-326.test.nl/swagger/index.html)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-326.test.nl/swagger/index.html)*, *ocpp-first*, *ocpp-second*, *[sbtservice](https://sbtservice-326.test.nl/swagger/index.html)*, *sparkJob-first*, *sparkJob-second*  
[TECH-713]: https://vandebron.atlassian.net/browse/TECH-713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TECH-713] Take tag into account for artifacts and build status cli commands

- releases/notes/1.4.11.md
- src/mpyl/steps/deploy/k8s/resources/dagster.py
- src/mpyl/utilities/helm/__init__.py
- tests/steps/deploy/dagster/dagster-user-deployments/values_with_global_service_account.yaml
- tests/steps/deploy/dagster/dagster-user-deployments/values_with_target_prod.yaml
- tests/steps/deploy/dagster/dagster-user-deployments/values_without_global_service_account.yaml
See here how resources of user code deployments should be set: https://github.com/dagster-io/dagster/blob/master/helm/dagster/charts/dagster-user-deployments/values.yaml#L114
This PR attempts to implement this. 
Check any pod starting with `udc` in grafana (e.g. [this one](https://grafana.prod-backend.vdbinfra.nl/k8s/clusters/c-r8bj6/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&refresh=10s&var-datasource=Prometheus&var-cluster=&var-namespace=dagster&var-pod=ucd-pc-production-correction-848fd5c799-vtl7x)) and conclude with me that the resources I set are sensible.
----
– This ticket is a reminder for Pieter to follow-up with Pim on resources – 
**Story**
Every app we …
> set default resources for all dagster repos

- src/mpyl/utilities/junit/__init__.py
branch: feature/TECH-722-check-for-dir
----
Sbt test step fails if test results our not in a predefined folder:
```
fn for fn in os.listdir(junit*result*path) if fn.endswith(".xml")                                                                                                               
FileNotFoundError: [Errno 2] No such file or directory: 'server/integration-tests/target/test-reports'                                                                              
❗ Failed with exception                                                                                                                                                                                
For Sbt Test on integrationTests at stage test   
```
[https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL …
> [TECH-722] Check if folder exists before trying to read the test suites

- MANIFEST.in
- releases/notes/1.4.13.md
- setup.py
- src/mpyl/reporting/targets/slack.py
- tests/reporting/targets/test_slack.py
branch: feature/TECH-506_ship_typing_info
----
See [180](https://github.com/Vandebron/mpyl/issues/180) 
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-341/2/display/redirect) ✅ Successful, started by _Jorg Post_  
🚀 *[cloudfront-service](https://cloudfront-service-341.test.nl/swagger/index.html)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-341.test.nl/swagger/index.html)*, *ocpp-first*, *ocpp-second*, *[sbtservice](https://sbtservice-341.test.nl/swagger/index.html)*, *sparkJob-first*, *sparkJob-second*  
[TECH-506]: https://vandebron.atlassian.net/browse/TECH-506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TECH-506] Ship typed file with mpyl

- README-dev.md
- releases/notes/1.4.15.md
- src/mpyl/steps/run_properties.py
- When constructing the run_properties, do not check the repo to figure out changes when we're doing a manual build or a build all
----
> do not figure out changes when doing manual build

- releases/notes/1.5.0.md
- src/mpyl/cli/projects.py
- tests/cli/test_resources/list_projects_text.txt
----
[p1709627138180799](https://vandebron.slack.com/archives/CGJDDBETU/p1709627138180799) 
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-373/2/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀 *[cloudfront-service](https://cloudfront-service-373.test.nl/swagger/index.html)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-373.test.nl/swagger/index.html)*, *ocpp-first*, *ocpp-second*, *[sbtservice](https://sbtservice-373.test.nl/swagger/index.html)*, *sparkJob-first*, *sparkJob-second*  
[GUILD-832]: https://vandebron.atlassian.net/browse/GUILD-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> do not filter project overrides from list of projects

- src/mpyl/cli/build.py
- tests/cli/test_resources/build_help_text.txt
This allows us to start a build from scratch by doing `mpyl build clean`, instead of having to support complex logic to understand when and how build plans should be used or cleaned up.
> feat: also clean the root .mpyl folder when calling mpyl build clean

- mpyl-reporter.py
- src/mpyl/artifacts/build_artifacts.py
- src/mpyl/build.py
- src/mpyl/cli/build.py
- src/mpyl/constants.py
- src/mpyl/project.py
- src/mpyl/stages/discovery.py
- src/mpyl/steps/build/docker_build.py
- tests/steps/test_steps.py
The name `build_plan` causes a lot of confusion since it clashes with the _Build_ stage and the `Sbt Build` and `Docker Build` steps. For this reason, after aligning all variables (from "build plan" or "build set" to "run plan") we're now also aligning the name of the file produced.
Replaces https://github.com/Vandebron/mpyl/pull/405
> refactor: renamed 'build plan' to 'run plan'

- src/mpyl/project_execution.py
- src/mpyl/stages/discovery.py
- src/mpyl/steps/build/post_docker_build.py
- src/mpyl/steps/models.py
- src/mpyl/steps/postdeploy/cypress_test.py
- tests/cli/commands/test_build.py
- tests/reporting/__init__.py
- tests/stages/test_discovery.py
- tests/steps/deploy/dagster/test_dagster.py
- tests/steps/deploy/ephemeral/test_ephemeral.py
- tests/steps/deploy/k8s/test_k8s.py
- tests/steps/post_deploy/test_cypress.py
- tests/steps/test_steps.py
- tests/test_resources/test_data.py
The current implementation needlessly links the fact that the current run can be cached to the production a hash of the contents, which means in some cases forcing a stage to run regardless of its caching status also prevents the next run from being cached.
This PR fixes that by ensuring that, regardless of whether the current run uses cached contents or re-runs the stage, a hash of the changes is always generated.
> feat: always produce hashed contents if changes are available

- src/mpyl/build.py
- src/mpyl/cli/build.py
In order to create a build plan for a tag release, `mpyl build status` should support a `--tag` parameter like the other build commands.
> feat: add tag parameter to build status

- src/mpyl/utilities/subprocess/__init__.py
This is technically not necessary anymore, but it might be good to simplify the code since the behaviour of `readline()` and `for line in file-object` was aligned in Python 3.
> refactor: simpler logging

- .github/setup-kind/action.yaml
- .github/workflows/build-package.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/tag.yml
- src/mpyl/schema/mpyl_config.schema.yml
- src/mpyl/utilities/docker/__init__.py
Schema documentation says 'aws' is the default registry provider. The
code now falls back on 'aws' when the provider is unspecified, making
what the documentation says true.
> Add docker as generic docker registry host

- src/mpyl/utilities/subprocess/__init__.py
> fix: avoid empty lines everywhere; also print messages sent to stderr

- .github/setup-kind/action.yaml
- .github/workflows/build-package.yml
- src/mpyl/steps/deploy/k8s/resources/traefik.py
- tests/steps/deploy/k8s/chart/templates/ingress-prod/minimalService-ingress-0-https.yaml
- tests/steps/deploy/k8s/chart/templates/ingress/minimalService-ingress-0-https.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-0-http.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-0-https.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-0-whitelist.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-1-http.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-1-https.yaml
- tests/steps/deploy/k8s/chart/templates/service/dockertest-ingress-1-whitelist.yaml
- tests/steps/deploy/k8s/templates/manifest.yaml
Our platform is not ready for this upgrade so we need to go back to the old `apiVersion` value.
> fix: revert back to the traefik.containo.us api version

- src/mpyl/schema/project.schema.yml
Otherwise we'll need an MPyL release every time we want to add a new pipeline in Github Actions.
> feat: make the pipeline field a freeform string

- src/mpyl/steps/deploy/k8s/chart.py
- tests/steps/deploy/k8s/chart/templates/job/job.yaml
MPyL inherently deletes and deploys `Job`s in K8s because they modify immutable fields. To ensure same behavior across ArgoCD implementations, we added this annotation.
> fix: Force ArgoCD to replace Jobs when syncing
