Vandebron/mpyl

src/pympl/project.py
src/pympl/projects/find.py
src/pympl/repo/__init__.py
src/pympl/stages/discovery.py
src/pympl/steps/build/dockerbuild.py
src/pympl/steps/build/echo.py
src/pympl/steps/deploy/echo.py
src/pympl/steps/step.py
src/pympl/steps/steps.py
tests/projects/repo/test_repo.py
tests/projects/test_load.py
tests/stages/test_discovery.py
tests/test_project.py

branch: feature/ARC-488-kubernetes-deploy

[ARC-488] Avoid shadowing of input parameter

---

Pipfile
Pipfile.lock
README.md
pympl-test-runner.py
src/pympl/steps/step.py
tests/projects/job/deployment/project.yml
workspace.yml

branch: feature/ARC-488-dagster-as-runner

[ARC-488] Prototype dagster based run

---

.github/workflows/build-package.yml
.pylintrc
Pipfile
Pipfile.lock
README.md
setup.py
src/pympl/project.py
src/pympl/schema/project.schema.json
src/pympl/stages/discovery.py
src/pympl/steps/build/__init__.py
src/pympl/steps/build/dockerbuild.py
src/pympl/steps/build/echo.py
src/pympl/steps/deploy/echo.py
src/pympl/steps/deploy/k8s/helm.py
src/pympl/steps/deploy/k8s/rancher.py
src/pympl/steps/deploy/k8s/resources.py
src/pympl/steps/deploy/k8s/service.py
src/pympl/steps/deploy/kubernetes.py
src/pympl/steps/models.py
src/pympl/steps/step.py
src/pympl/steps/steps.py
tests/steps/deploy/k8s/chart/templates/deployment.yaml
tests/steps/deploy/k8s/test_k8s.py
tests/test_project.py
tests/test_resources/test_project.yml

branch: feature/ARC-532-introduce-pylint

[ARC-532] Enable Pylint and fix issues

---

README-dev.md
README.md

branch: feature/ARC-565-add_dev_instructions

[ARC-565] Add readme about troubleshooting pipenv

---

.github/workflows/build-package.yml
.github/workflows/release.yml
Pipfile
setup.py
tests/projects/test_load.py
tests/stages/test_discovery.py

Publishes PR to https://test.pypi.org/project/mpyl/
branch: feature/ARC-534-automate-relase-process

[ARC-534] Publish PR on test.pypi.org

---

.github/workflows/docs.yml
.gitignore

fix docs no directory

---

Jenkinsfile
config.yml
mpyl-example.py
src/mpyl/project.py
src/mpyl/reporting/targets/github.py
src/mpyl/schema/mpyl_config.schema.yml
src/mpyl/steps/steps.py
src/mpyl/steps/test/after_test.py
src/mpyl/steps/test/before_test.py
src/mpyl/steps/test/dockertest.py
src/mpyl/steps/test/sbt.py
src/mpyl/utilities/docker/__init__.py
tests/projects/service/deployment/docker-compose-test.yml

branch: feature/ARC-591-docker-compose-start

[ARC-591] Create before test step that starts containers

---

README.md
mpyl-example.py
src/mpyl/__init__.py
src/mpyl/cli/build/mpyl.py
src/mpyl/cli/commands/build.py
src/mpyl/reporting/formatting/markdown.py
tests/reporting/test_resources/markdown_run.md
tests/reporting/test_resources/markdown_run_slack.md
tests/reporting/test_resources/markdown_run_with_plan.md

branch: feature/ARC-584-cli-small-fixes

[ARC-584] Small fixes

---

.github/workflows/build-package.yml
README-usage.md
config.yml
src/mpyl/cli/__init__.py
src/mpyl/cli/build/jenkins.py
src/mpyl/cli/commands/__init__.py
src/mpyl/cli/commands/build.py
src/mpyl/cli/commands/projects.py
src/mpyl/reporting/formatting/markdown.py
src/mpyl/reporting/targets/github.py
src/mpyl/reporting/targets/slack.py
src/mpyl/schema/mpyl_config.schema.yml
src/mpyl/schema/project.schema.yml
src/mpyl/steps/deploy/k8s/chart.py
src/mpyl/steps/run.py
src/mpyl/steps/steps.py
src/mpyl/utilities/github/__init__.py
src/mpyl/utilities/repo/__init__.py
tests/reporting/test_resources/markdown_run.md
tests/reporting/test_resources/markdown_run_slack.md
tests/reporting/test_resources/markdown_run_with_plan.md
tests/reporting/test_resources/test_run_summary.md
tests/test_resources/config.yml

branch: feature/ARC-595-cli-fixes

[ARC-595] Only print exception when verbose

---

Pipfile.lock
README-usage.md
src/mpyl/schema/run_properties.schema.yml
tests/steps/test_models.py
tests/test_resources/run_properties.yml

fixed comments from this PR: 
https://github.com/Vandebron/mpyl/pull/62

fix build parameters comments

---

Jenkinsfile

branch: feature/TECH-289-introduce-custom-mpyl-agent

[TECH-289] Set agent affinity to mpyl specific node

---

.github/workflows/build-package.yml
src/mpyl/cli/build.py
src/mpyl/cli/commands/build/mpyl.py
src/mpyl/reporting/formatting/markdown.py
src/mpyl/steps/build/docker_after_build.py
src/mpyl/steps/build/dockerbuild.py
src/mpyl/steps/deploy/kubernetes.py
src/mpyl/steps/steps.py
src/mpyl/utilities/docker/__init__.py
tests/reporting/formatting/test_resources/markdown_run_with_plan.md
tests/reporting/targets/test_resources/markdown_run_slack.md
tests/steps/deploy/k8s/test_k8s.py

branch: feature/TECH-272-fix-frontend-deploys

[TECH-272] Improve deployed service url

---

.github/workflows/build-package.yml
Jenkinsfile
run_properties.yml
src/mpyl/cli/commands/build/mpyl.py
src/mpyl/schema/mpyl_config.schema.yml
src/mpyl/schema/run_properties.schema.yml
src/mpyl/steps/deploy/k8s/helm.py
src/mpyl/steps/models.py
tests/steps/test_steps.py
tests/test_resources/run_properties.yml
tests/test_resources/test_data.py

branch: fix/TECH-409-fix-helm-list

[TECH-409] Make name match exact

---

src/mpyl/steps/steps.py

branch: fix/TECH-424-deploy-continues-in-spite-of-test-failures

[TECH-424] Consider after step as failed if main step failed

---

.coveragerc
mpyl-example.py
src/mpyl/reporting/targets/__init__.py
src/mpyl/reporting/targets/github.py
src/mpyl/reporting/targets/jira.py
src/mpyl/reporting/targets/slack.py
src/mpyl/steps/run.py
tests/reporting/targets/test_jira.py
tests/reporting/targets/test_reporters.py
tests/test_resources/test_data.py

branch: fix/TECH-423-accumulate-and-log-report-failures
monorepo counterpart: https://github.com/Vandebron/Vandebron/pull/10481

[TECH-423] Accumulate and log reporting failures

---

mpyl_config.example.yml
src/mpyl/cli/build.py
src/mpyl/cli/commands/build/jenkins.py
src/mpyl/cli/commands/build/mpyl.py
src/mpyl/cli/projects.py
src/mpyl/reporting/targets/github.py
src/mpyl/reporting/targets/jira.py
src/mpyl/schema/mpyl_config.schema.yml
src/mpyl/steps/deploy/kubernetes.py
src/mpyl/steps/deploy/kubernetes_job.py
src/mpyl/steps/deploy/kubernetes_spark_job.py
src/mpyl/utilities/repo/__init__.py
tests/projects/repo/test_repo.py
tests/reporting/targets/test_resources/markdown_jira.md
tests/reporting/targets/test_resources/markdown_jira_github.md
tests/test_resources/mpyl_config.yml
tests/test_resources/test_data.py

branch: feature/TECH-437-as-user-of-m-py-l-i-dont-want-to-depend-on-jenkins-to-have-pulled-in-branches-up-front
Monorepo: https://github.com/Vandebron/Vandebron/pull/10531

[TECH-437] Fetch remote if necessary, via config

---

src/mpyl/steps/deploy/k8s/chart.py
tests/steps/deploy/k8s/chart/templates/service/deployment.yaml

branch: feature/TECH-442_remove_hostport

[TECH-442] Remove hostport from deployment

---

.github/workflows/build-package.yml
src/mpyl/reporting/formatting/text.py
src/mpyl/reporting/targets/github.py
src/mpyl/reporting/targets/jira.py
src/mpyl/steps/deploy/k8s/chart.py
tests/reporting/formatting/test_resources/simple_run.txt
tests/reporting/formatting/test_resources/simple_test.txt
tests/reporting/targets/test_jira.py
tests/reporting/targets/test_resources/markdown_jira.md
tests/reporting/targets/test_resources/markdown_jira_github.md
tests/reporting/targets/test_resources/markdown_jira_ticket_to_github.md
tests/steps/deploy/k8s/chart/templates/cronjob/cronjob.yaml
tests/steps/deploy/k8s/chart/templates/job/job.yaml

----
📕 [TECH-300](https://vandebron.atlassian.net/browse/TECH-300) Create tag deployments ![danielkoves@vandebron.nl](https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/6151b89d72f6970069e87968/a94f6e9a-3a6b-434f-926f-f4aa079c6a59/24) 
* extract changes from the pull request’s merge commit → check DetectChanges.groovy in mpl-modules
* instead of comparing the branch with master
* Create tag creation logic in mpyl repo → copy mpl-modules
Testing:
- locally: build properties set the tag
- or in jenkins
🏗️ Build [6](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-132/6/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀  *enrichChargeSessionsJob*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-132.test.nl/)*, …

feature/TECH 300 Multiple improvements

---

.gitignore
.idea/.gitignore
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/jsonSchemas.xml
.idea/markdown.xml
.idea/misc.xml
.idea/modules.xml
.idea/sbt.xml
.idea/vcs.xml
mpyl.iml

- Bring general intellij settings under version control
- Add Intellij files
- Add .idea gitignore
Note: #128 may be closed
----

feature/TECH XXX bring intellij project settings under vcs

---

Pipfile
Pipfile.lock
src/mpyl/cli/commands/build/__init__.py
src/mpyl/cli/commands/build/jenkins.py
src/mpyl/utilities/jenkins/runner.py

Current sound at end of build is OS (Mac) specific. It will result in an error on Linux or Windows machines
----
📕 [TECH-438](https://vandebron.atlassian.net/browse/TECH-438) Usability issues with MPyL ![sam@vandebron.nl](https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:73eb6738-a8dc-4e71-beb2-16761407e54e/44a3caa2-b498-4ee1-927d-bdb0901a683e/24) 
[p1685111170053379](https://vandebron.slack.com/archives/C04KP2UFMMJ/p1685111170053379) 
🏗️ Build [7](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-129/7/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀  *enrichChargeSessionsJob*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-129.test.nl/)*, *[sbtservice](https://sbtservice-129.test.nl/)*  
[TECH-438]: …

Play sound on all OS

---

run_properties.yml
src/mpyl/cli/commands/build/mpyl.py
src/mpyl/reporting/formatting/markdown.py
src/mpyl/schema/mpyl_config.schema.yml
src/mpyl/schema/run_properties.schema.yml
src/mpyl/steps/models.py
src/mpyl/steps/postdeploy/cypress_test.py
src/mpyl/steps/steps.py
src/mpyl/utilities/cypress/__init__.py
src/mpyl/utilities/docker/__init__.py
tests/reporting/formatting/test_resources/markdown_run.md
tests/reporting/formatting/test_resources/markdown_run_with_exception.md
tests/reporting/formatting/test_resources/markdown_run_with_plan.md
tests/reporting/targets/test_resources/markdown_run_slack.md
tests/steps/test_steps.py
tests/test_resources/.gitignore
tests/test_resources/cypress/Dockerfile-mpyl
tests/test_resources/cypress/cypress.config.js
tests/test_resources/cypress/cypress.env.json.example
tests/test_resources/cypress/package.json
tests/test_resources/cypress/tsconfig.json
tests/test_resources/cypress/yarn.lock
tests/test_resources/run_properties.yml
tests/test_resources/test_data.py

branch: feature/TECH-394-update-cypress-logic-for-monorepo
----
📕 [TECH-394](https://vandebron.atlassian.net/browse/TECH-394) Integrate cypress suites into mpyl ![jorgpost@vandebron.nl](https://secure.gravatar.com/avatar/4438c9af956adc9562fde9f029f624e2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FJP-3.png) 
Make sure that certain cypress suites get triggered for certain projects when specified in the project.yml.
🏗️ Build [13](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-114/13/display/redirect) ✅ Successful, started by _Jorg Post_  
🚀  *enrichChargeSessionsJob*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-114.test.nl/)*, *[sbtservice](https://sbtservice-114.test.nl/)*  
[TECH-394]: …

[TECH-394] Improve cypress execute step

---

.github/workflows/docs.yml

Add python setup to docs workflow

---

.github/workflows/docs.yml

Add python version to docs workflow

---

Pipfile

branch: feature/TECH-394-implement-parallel-runs
----
📕 [TECH-394](https://vandebron.atlassian.net/browse/TECH-394) Integrate cypress suites into mpyl <img src="https://secure.gravatar.com/avatar/4438c9af956adc9562fde9f029f624e2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FJP-3.png" width="24" height="24" alt="jorgpost@vandebron.nl" /> 
Make sure that certain cypress suites get triggered for certain projects when specified in the project.yml.
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-151/2/display/redirect) ✅ Successful, started by _Jorg Post_  
🚀 *[cloudfront-service](https://cloudfront-service-151.test.nl/)*, *enrichChargeSessionsJob*, *job*, *kong-sync*, …

[TECH-394] Make sure we only create a whl build file

---

src/mpyl/schema/run_properties.schema.yml
src/mpyl/utilities/repo/__init__.py

- Fix getting changes for branches with one commit
- Put Acceptance back as valid target
----

Fix getting changes for single commit branches

---

src/mpyl/cli/repository.py
src/mpyl/utilities/repo/__init__.py

branch: feature/TECH-543-fix-git-fetch-issue
----
🏗️ Build [2](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-190/2/display/redirect) ✅ Successful, started by _Jorg Post_  
🚀 *[cloudfront-service](https://cloudfront-service-190.test.nl/)*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-190.test.nl/)*, *[sbtservice](https://sbtservice-190.test.nl/)*, *sparkJob*  
[TECH-543]: https://vandebron.atlassian.net/browse/TECH-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TECH-543] First delete the local pr branch to prevent conflicts

---

src/mpyl/cli/repository.py
src/mpyl/utilities/repo/__init__.py

branch: feature/TECH-507-argo-cd-support
----
🏗️ Build [3](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-229/3/display/redirect) ✅ Successful, started by _Jorg Post_  
🚀 *[cloudfront-service](https://cloudfront-service-229.test.nl/)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-229.test.nl/)*, *[sbtservice](https://sbtservice-229.test.nl/)*, *sparkJob*  
[TECH-567]: https://vandebron.atlassian.net/browse/TECH-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TECH-507] Try local main first and only then origin/main

---

README-usage.md

branch: feature/TECH-513_quick_setup_tutorial
----
Currently information on how to quickly “run” mpyl is scattered around in the pip library description, github readme and `mpyl health` commands.
Centralise them and create a short tutorial and how to start from scratch with mpyl and deploy a PR.
----
Mention MPyL in the monorepo README and link this tutorial there
🏗️ Build [3](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-234/3/display/redirect) ✅ Successful, started by _Sam Theisens_  
🚀 *[cloudfront-service](https://cloudfront-service-234.test.nl/)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-234.test.nl/)*, *[sbtservice](https://sbtservice-234.test.nl/)*, *sparkJob*  
[TECH-513]: …

[TECH-513] Update usage readme

---

.github/workflows/release.yml
release.py

Release 1.2.0rc2

---

src/mpyl/steps/build/docker_after_build.py
src/mpyl/steps/deploy/echo.py
src/mpyl/steps/deploy/k8s/chart.py
src/mpyl/steps/models.py
src/mpyl/steps/steps.py
src/mpyl/steps/test/dockertest.py
src/mpyl/utilities/docker/__init__.py

In order to speed up gha builds:
```
INFO     #8 importing cache manifest from ghcr.io/samtheisens/nodeservice:pr-6-test                                                                  
INFO     #8 DONE 0.2s                                                                                                                                
INFO                                                                                                                                                 
INFO     #6  load build context                                                                                                                      
INFO     #6 transferring context: 683B done                                                                                                          
INFO     #6 …
```

Cache docker test results

---

src/mpyl/steps/deploy/kubernetes.py
src/mpyl/steps/steps.py

- Remove implicit deploy logic after PROD deployment
- Attempt to fix swagger links
[TECH-565]: https://vandebron.atlassian.net/browse/TECH-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TECH-565]: https://vandebron.atlassian.net/browse/TECH-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
----
🏗️ Build [3](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-226/3/display/redirect) ✅ Successful, started by _Daniel Koves_  
🚀 *[cloudfront-service](https://cloudfront-service-226.test.nl/swagger/index.html)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-226.test.nl/swagger/index.html)*, …

feature/TECH 565 Remove implicit deploy logic

---

src/mpyl/cli/commands/health/checks.py
src/mpyl/projects/versioning.py
src/mpyl/schema/run_properties.schema.yml
tests/projects/test_versioning.py
tests/test_resources/upgrades/run_properties_base.yml
tests/test_resources/upgrades/run_properties_upgraded.yml

branch: feature/TECH-491-upgrade-build-properties
----
Improve and extend our CI-CD capabilities
**DoD:** 
* MPL is marked as deprecated
* Most development run on MPyL
🏗️ Build [3](https://jenkins.k8s-serv-backend.vdbinfra.nl/job/MPyL%20Pipeline%20-%20Test/job/PR-257/3/display/redirect) ✅ Successful, started by _Sam Theisens_  
🚀 *[cloudfront-service](https://cloudfront-service-257.test.nl/swagger/index.html)*, *example-dagster-user-code*, *job*, *kong-sync*, *[nodeservice](https://nodeservice-257.test.nl/swagger/index.html)*, *[sbtservice](https://sbtservice-257.test.nl/swagger/index.html)*, *sparkJob*  
[TECH-491]: https://vandebron.atlassian.net/browse/TECH-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TECH-491] Upgrade run properties

---

src/mpyl/steps/build/skip.py
src/mpyl/steps/test/skip.py

Add skip build, test steps
----

Add skip build/test step

---

releases/notes/1.4.3.md
src/mpyl/steps/deploy/cloudfront_kubernetes_deploy.py
src/mpyl/steps/deploy/ephemeral_docker_deploy.py
src/mpyl/utilities/docker/__init__.py

fix cloudfront deploy

---

releases/notes/1.4.5.md

----
[2926](https://github.com/Vandebron/scripting/pull/2926)  needs to be merged first (linting and updating of runner and config)
----
to test the behaviour of two user-code repositories co-existing (MPL and MPyL dpeloyed) I would like to:
test out a usercode deployment on Acceptance:
* make backup of the workspace.yml file (copy YAML and store locally)
* deploy a tag with MPL (suf or so)
* then deploy the same tag with MPyL
* check if everything’s still working
the results of this test will decide whether a hard-switch for ALL projects is needed or what steps can be done to make a softer switch happen/.
----
check in with Tim (platform) about the workspace-configmap backup
----
check on how to deprecate a Jenkinspipeline?
----
* fix linting errors (check mpyl lint --all)
**** deprecate …

Prepare release notes 1.4.5

---

releases/notes/1.4.7.md
src/mpyl/steps/build/docker_build.py
src/mpyl/steps/deploy/cloudfront_kubernetes_deploy.py
src/mpyl/steps/deploy/ephemeral_docker_deploy.py
src/mpyl/steps/test/dockertest.py
src/mpyl/utilities/docker/__init__.py

Set `DOCKER_IMAGE` with full path

---

releases/notes/1.4.8.md
src/mpyl/steps/deploy/k8s/chart.py
tests/steps/deploy/k8s/chart/templates/cronjob/cronjob.yaml
tests/steps/deploy/k8s/chart/templates/job/job.yaml
tests/test_resources/test_cron_job_project.yml
tests/test_resources/test_job_project.yml

Add command and args to job

---

releases/notes/1.4.10.md

branch: featute/TECH-713-fix-tag-builds

[TECH-713] Add release note for v1.4.10

---

src/mpyl/utilities/docker/__init__.py

Fix check for registry provider

---

tests/projects/cloudfront/deployment/project.yml
tests/projects/sbt-service/deployment/project.yml
tests/projects/service/deployment/project.yml
tests/projects/spark-job/deployment/project.yml
tests/test_resources/cypress/Dockerfile-mpyl

downsize mpyl example projects

---

src/mpyl/artifacts/build_artifacts.py

don't pull first before pushing

---

mpyl_config.example.yml
src/mpyl/schema/mpyl_config.schema.yml
src/mpyl/utilities/docker/__init__.py

remove lifecycle policy

---

releases/notes/1.5.1.md
src/mpyl/stages/discovery.py

- Always add to deploy stage changes to build plan
- Add a release note for v1.5.1

feature/GUILD XXX fix deploy stage build plan

---

src/mpyl/reporting/formatting/markdown.py
src/mpyl/stages/discovery.py
tests/reporting/__init__.py
tests/reporting/formatting/test_resources/markdown_run.md
tests/reporting/formatting/test_resources/markdown_run_multiple_urls.md
tests/reporting/formatting/test_resources/markdown_run_with_exception.md
tests/reporting/formatting/test_resources/markdown_run_with_plan.md
tests/reporting/targets/test_resources/markdown_jira_ticket_to_github.md
tests/reporting/targets/test_resources/markdown_run_slack.md

Don't add a tab before the projects list since it doesn't work in slack

---

mpyl-dagster-example.py
src/mpyl/build.py
src/mpyl/cli/build.py
src/mpyl/stages/discovery.py
src/mpyl/steps/run_properties.py
tests/stages/test_discovery.py

Split from https://github.com/Vandebron/mpyl/pull/400 to make reviewing easier.
Also did some minor renames to other fields for clarity purposes.

refactor: aligned all ocurrences of 'build set' and 'build plan' to 'run plan'

---

src/mpyl/steps/deploy/k8s/__init__.py

Do not fail if the namespace we're trying to upsert already exists.

feat: do not fail if a namespace already exists

---

src/mpyl/steps/deploy/bpm/modeler.py

branch: fix/BPMN-362-milestone-creation-relative-imports

[BPMN-362] Use relative instead of circular imports

---

src/mpyl/project.py
src/mpyl/schema/project.schema.yml
tests/reporting/__init__.py
tests/steps/test_steps.py
tests/test_resources/test_data.py

Replaces:
* https://github.com/Vandebron/mpyl/pull/453

feat: new optional pipeline field in project.yml

---

src/mpyl/build.py
src/mpyl/steps/test/before_test.py

To pull in local base images when they are used in the docker-compose

Log in to docker registry so we can pull in images when necessary

---

releases/notes/1.8.6.md
src/mpyl/steps/executor.py

- **Make progress logging output more concise**
- **Add release note**

improve logging output
